FROM php:7.0

RUN mkdir -p /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/phptest

COPY helloworld.php /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/phptest

WORKDIR /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/phptest

CMD php helloworld.php