# The interpreter.
FROM python:3.8
# Created program.
RUN mkdir -p /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/pythontest
# Copy files.
COPY helloworld.py /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/pythontest
# Sets the working directory.
WORKDIR /Project/GIT/AndriiVasylenkoML/docker/Its_as_simple_as_it_gets/pythontest
# Comand for run program.
CMD python helloworld.py